on: push
name: Deploy to nashural.ru
jobs:
  deploy-ftp:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2.3.2

    - name: Use node 15
      uses: actions/setup-node@v2-beta
      with:
        node-version: '15'

    - name: Build project
      run: |
        npm install --production
        npm run build
      env:
        PUBLIC_URL: /map/
        REACT_APP_SEARCH_URL: https://nashural.ru/map
        REACT_APP_YMAPS_API_KEY: 137e6a7f-ee29-403c-be2d-8021680117ab
        REACT_APP_NONCE: 1237

    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: nashural.ru
        username: nashur_0
        password: ${{ secrets.ftp_password }}
        local-dir: ./build/
        server-dir: /map/
